#!/usr/bin/env bash
# Shebang for better detection of file type

export DIST_NAME=MainsailOS
export DIST_VERSION=0.7.1
export BASE_IMAGE_ENLARGEROOT=4000
export MODULES="base,pkgupgrade,mainsailos(net,piconfig,klipper,is_req_preinstall,moonraker,timelapse,mainsail,crowsnest,klipperscreen,sonar,password-for-sudo),postrename"
export BASE_RELEASE_COMPRESS=yes
export BASE_IMAGE_RESIZEROOT=600
